# Generated by Django 4.2.17 on 2026-01-20 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.DecimalField(blank=True, decimal_places=2, help_text='Protein in grams', max_digits=5, null=True)),
                ('carbs', models.DecimalField(blank=True, decimal_places=2, help_text='Carbs in grams', max_digits=5, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=2, help_text='Fat in grams', max_digits=5, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in grams or servings', max_digits=5)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in km', max_digits=5, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
