# Generated by Django 4.2.17 on 2026-01-20 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('muscle_gain', 'Muscle Gain'), ('maintain_weight', 'Maintain Weight'), ('increase_fitness', 'Increase Fitness'), ('improve_endurance', 'Improve Endurance')], default='maintain_weight', max_length=50)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Target weight in kg', max_digits=5, null=True)),
                ('target_calories_burn', models.PositiveIntegerField(default=2000, help_text='Daily calories to burn')),
                ('target_calories_consume', models.PositiveIntegerField(default=2000, help_text='Daily calories to consume')),
                ('target_protein', models.DecimalField(decimal_places=2, default=100, help_text='Daily protein target in grams', max_digits=5)),
                ('target_activity_days', models.PositiveIntegerField(default=3, help_text='Days per week for activity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
