# Generated by Django 4.2.17 on 2026-01-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_activity_user_alter_nutritionentry_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nutritionentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='user',
        ),
    ]
