name: Simulate Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  simulate:
    name: Simulate Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run application
        run: |
          docker-compose up -d
          sleep 10  # Wait for services to start
          
      - name: Check application health
        run: |
          curl --fail http://localhost:8000/health/ || exit 1
          
      - name: Run API tests
        run: |
          docker-compose exec app python manage.py test api.tests
          
      - name: Cleanup
        if: always()
        run: docker-compose down 